//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecuperacaoCustoAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contexto : DbContext
    {
        public Contexto()
            : base("name=Contexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CR> CR { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Sessao> Sessao { get; set; }
        public virtual DbSet<Ciclo> Ciclo { get; set; }
        public virtual DbSet<MesCiclo> MesCiclo { get; set; }
        public virtual DbSet<RecuperacaoCusto> RecuperacaoCusto { get; set; }
        public virtual DbSet<RecuperacaoCustoMes> RecuperacaoCustoMes { get; set; }
        public virtual DbSet<TipoRecuperacao> TipoRecuperacao { get; set; }
    }
}
