//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecuperacaoCustoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecuperacaoCustoMes
    {
        public int CodRecuperacao { get; set; }
        public int CodMesCiclo { get; set; }
        public float Valor { get; set; }
    
        public virtual MesCiclo MesCiclo { get; set; }
        public virtual RecuperacaoCusto RecuperacaoCusto { get; set; }
    }
}
