//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecuperacaoCustoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioTransfReceita
    {
        public string Empresa { get; set; }
        public string UN { get; set; }
        public string UR { get; set; }
        public string Conta_Contabil { get; set; }
        public string CR { get; set; }
        public string Produto { get; set; }
        public string Intercompany { get; set; }
        public string UF { get; set; }
        public string Cliente { get; set; }
        public string Reserva1 { get; set; }
        public string Reserva2 { get; set; }
        public float Debito { get; set; }
        public float Credito { get; set; }
        public string ItemFaturamento { get; set; }
        public string Documento { get; set; }
        public string NF { get; set; }
        public System.DateTime DataEmissao { get; set; }
        public string Historico { get; set; }
        public string Tipo { get; set; }
    }
}
